[build]
  base      = "fitness-app"
  command   = "npm install && NODE_OPTIONS=--openssl-legacy-provider npm run build"
  publish   = "fitness-app/build"

[build.environment]
  # use Node 18 so your Firebase packages are happy
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200